export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/generate/index',
    'pages/advanced-settings/index',
    'pages/mine/index',
    'pages/login/index',
    'pages/preview/index',
    'pages/post-detail/index',
    'pages/my-post-detail/index',
    'pages/publish/index',
    'pages/publish-success/index',
    'pages/drafts/index',
    'pages/my-likes/index',
    'pages/my-favorites/index',
    'pages/my-posts/index',
    'pages/beans/index',
    'pages/feedback/index',
    'pages/feedback-form/index',
    'pages/admin-review/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'happy拼豆嘛',
    navigationBarTextStyle: 'black',
  },
})
